languages: node_js

node_js:
  - '12.13.1'

cache: yarn

install:
  - yarn ci

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
